apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: https://github.com/ibm-cloud-architecture/refarch-eda-store-simulator.git
  labels:
    app.kubernetes.io/name: store-simulator
    app.openshift.io/runtime: quarkus
  name: store-simulator
spec:
  replicas: 1
  selector:
    app.kubernetes.io/name: store-simulator
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-url: https://github.com/ibm-cloud-architecture/refarch-eda-store-simulator.git
      labels:
        app.kubernetes.io/name: store-simulator
        app.openshift.io/runtime: quarkus
    spec:
      containers:
      - args:
        - -Dquarkus.http.host=0.0.0.0
        - -Djava.util.logging.manager=org.jboss.logmanager.LogManager
        - -Djavax.net.ssl.trustStoreType=jks
        - -Djavax.net.ssl.trustStore=/deployments/certs/mq-tls/mq-tls.jks
        - -Djavax.net.ssl.trustStorePassword=my-mq-password
        - -jar
        - /deployments/quarkus-run.jar
        command:
        - java
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KAFKA_SSL_TRUSTSTORE_LOCATION
          value: /deployments/certs/server/ca.p12
        - name: KAFKA_SSL_TRUSTSTORE_TYPE
          value: PKCS12
        - name: KAFKA_SECURITY_PROTOCOL
          value: SSL
        - name: KAFKA_USER
          value: tls-user
        - name: KAFKA_BROKERS
          value: lab-kafka-bootstrap.jb-lab.svc:9093
        - name: MQ_CIPHER_SUITE
          value: TLS12ORHIGHER
        - name: USER_CERT_PATH
          value: /deployments/certs/user/user.p12
        - name: USER_CERT_PWD
          valueFrom:
            secretKeyRef:
              key: user.password
              name: tls-user
              optional: true
        - name: KAFKA_CERT_PWD
          valueFrom:
            secretKeyRef:
              key: ca.password
              name: lab-kafka-cluster-ca-cert
              optional: true
        - name: KAFKA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: user.password
              name: tls-user
              optional: true
        - name: KAFKA_CERT_PATH
          value: /deployments/certs/server/ca.p12
        - name: MQ_CCDT_URL
          value: /deployments/certs/mq-ccdt/mq-ccdt.json
        - name: JAVA_APP_JAR
          value: /deployments/quarkus-run.jar
        envFrom:
        - configMapRef:
            name: store-simulator-cm
        image: quay.io/ibmcase/eda-store-simulator
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: store-simulator
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /deployments/certs/server
          name: kafka-cert
          readOnly: false
          subPath: ""
        - mountPath: /deployments/certs/mq-ccdt
          name: mq-ccdt-config
          readOnly: false
          subPath: ""
        - mountPath: /deployments/certs/mq-tls
          name: mq-tls-truststore
          readOnly: false
          subPath: ""
        - mountPath: /deployments/certs/user
          name: user-cert
          readOnly: false
          subPath: ""
      serviceAccount: store-simulator
      volumes:
      - name: kafka-cert
        secret:
          defaultMode: 384
          optional: true
          secretName: lab-kafka-cluster-ca-cert
      - name: mq-tls-truststore
        secret:
          defaultMode: 384
          optional: false
          secretName: store-simulator-mq-truststore
      - name: user-cert
        secret:
          defaultMode: 384
          optional: true
          secretName: tls-user
      - name: mq-ccdt-config
        configMap:
          defaultMode: 384
          optional: false
          name: mq-ccdt-config
